k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_meisterlabs-prod_europe-west3_mindmeister-production
  currentCluster: gke_meisterlabs-prod_europe-west3_mindmeister-production
  clusters:
    gke_meisterlabs-prod_europe-west3_meistertask-production:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - refinery
        - production
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_meisterlabs-prod_europe-west3_mindmeister-production:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - refinery
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_meisterlabs-staging_europe-west1_accounts-staging:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - leia
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_meisterlabs-staging_europe-west1_meistertask-staging:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
        - refinery
        - grafana
        - leia
        - develop
        - hal
        - chewie
        - jarjar
        - kube-system
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-hschne
